### ISSUE TITLE
Unable to Parse My username

### ISSUE THREAD

**Issue by Anmol-SlayerOP** [HwangTaehyun/github-repository-contribution-stats#23]
It is not able to correctly read my username as   Anmol-SlayerOP
hence unable to add your widgets
showing this error
![image](https://github.com/user-attachments/assets/e3e7d445-9d5b-4005-912c-1d372a2331c8)

**Comment by HwangTaehyun** [comment]
@Anmol-SlayerOP I think we have some errors on the following code.
https://github.com/HwangTaehyun/github-repository-contribution-stats/blob/a90e0e0904ff6b42b631541628f360eb85752a3d/src/cards/stats-card.ts#L199

If there is no contribution (If statItems' length is 0, there is currently an error and there seems to be a problem because there is no defense logic for this.
